kind: pipeline
name: default

steps:
  - name: integration-test
    image: justinbarrick/hone
    commands:
      - hone integration-test
    environment:
      VAULT_TOKEN:
        from_secret: VAULT_TOKEN
    when:
      event: push

  - name: build
    image: justinbarrick/hone
    commands:
      - hone
    environment:
      VAULT_TOKEN:
        from_secret: VAULT_TOKEN
    when:
      event: push
